hodor/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'hodor'

urlpatterns = []

if settings.WEB_HODOR_ENABLE_WEB:
    urlpatterns = [
        path('', RedirectView.as_view(pattern_name='hodor:tournament_home')),
        path('hodor/', views.simul, name='simul'),
        path('tournaments/', views.tournament_home, name='tournament_home'),
        path('tournaments/builder/', views.tournament_builder, name='tournament_builder'),
        path('tournaments/simul/', views.tournament_simul, name='tournament_simul'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/', views.tournament_detail, name='tournament_detail'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/result/', views.tournament_result, name='tournament_result'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/admin/', views.tournament_admin, name='tournament_admin'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/execute/', views.tournament_execute, name='tournament_execute'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/validate/', views.tournament_validate, name='tournament_validate'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/result/<int:player_id>/', views.tournament_result_player, name='tournament_result_player'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/result/<int:attacker_id>-vs-<int:defender_id>/', views.tournament_result_match, name='tournament_result_match'),
        path('ajax/units/', views.ajax_units, name='ajax_units'),
        path('info/units/', views.info_units, name='info_units'),
        path('info/sizes/', views.info_sizes, name='info_sizes'),
    ]

urlpatterns.append(
    path('ajax/simulate-gate/', views.ajax_simulate_gate, name='ajax_simulate_gate')
)

hodor/views.py
# Create your views here.
import json
import traceback

import jsonpickle
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from hodor.combat.battle import Battle
from hodor.combat.combatmodel import SpellInCombat
from hodor.combat.simulator import simulate_all
from hodor.combat.userinput import process_user_input, parse_input_file_autodetect, new_gate_units, parse_json
from hodor.data.provider import all_regular_units, combat_spell, COUNTERSPELL_ID, all_combat_spell_groups
from hodor.json import UnitFullInfoEncoder
from hodor.models import Tournament, TournamentResult, TournamentSubmission, UserSimulation
from hodor.tournament import execute_tournament, battle_one_on_one


def simul(request):
    if not settings.WEB_HODOR_ALLOW_PRECISE_SIMULATION:
        return render(request, 'hodor/simul/simul_disabled.html')

    # simulate heavily pre-scripted combat

    battles = []
    units_input = None
    gate_number = None
    input_gate_passed = None

    if request.method == 'POST':
        units_input = request.POST['units']
        gate_number = int(request.POST['gate_number'])
        input_gate_passed = int(request.POST['input_gate_passed']) if request.POST['input_gate_passed'] != '' else None

        gate_units_sets = new_gate_units(gate_number=gate_number, players_passed=input_gate_passed)

        for index, gate_units in enumerate(gate_units_sets):
            user_units = process_user_input(parse_input_file_autodetect(units_input))
            battle = Battle(user_units + gate_units, gate_number=gate_number, label='Army %d' % index,
                            verbose_result=True)
            battle.execute_battle()
            battles.append(battle)

        units_input = "\n".join('%s;%s;%d' % (u.nazev, ("%.4f" % (u.zkusenost / 100.0)).rstrip("0."), u.pocet) for u in
                                process_user_input(parse_input_file_autodetect(units_input)))

    return render(request, 'hodor/simul/simul.html', {
        'battles': battles,
        'units_input': units_input,
        'gate_number': gate_number,
        'input_gate_passed': input_gate_passed,
    })


@require_POST
@csrf_exempt  # no need for csrf here, on the other hand GET does not make sense
def ajax_simulate_gate(request):
    data = json.loads(request.body)

    attacker_units = process_user_input(parse_json(data['units']))
    battles = simulate_all(attacker_units, data['gate'], data['already_passed'])

    result = []

    for battle in battles:
        if battle.result_attacker + 0.05 < battle.result_defender:
            # solid victory
            result.append([battle.label, 'win'])
        elif battle.result_attacker < battle.result_defender:
            # close victory
            result.append([battle.label, 'near-win'])
        elif battle.result_attacker - 0.05 < battle.result_defender:
            # close defeat
            result.append([battle.label, 'near-loss'])
        else:
            # solid defeat
            result.append([battle.label, 'loss'])

    return JsonResponse({'result': result})


@cache_page(60 * 60)
def ajax_units(request):
    return JsonResponse({'units': all_regular_units()}, UnitFullInfoEncoder)


@permission_required('hodor.add_tournamentsubmission', raise_exception=True)
def tournament_admin(request, tournament_id: int, tournament_slug: str):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_admin', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug}))

    tournament_results = {}
    for result in tournament.tournamentresult_set.all():
        if result.attacker_id not in tournament_results:
            tournament_results[result.attacker_id] = {}

        tournament_results[result.attacker_id][result.defender_id] = result

    return render(request, 'hodor/tournament/admin.html', {
        'tournament': tournament,
        'tournament_submissions': tournament.tournamentsubmission_set.order_by(*(['valid'] + tournament.result_type_submission_order_by())).all(),
        'tournament_results': tournament_results,
    })


def tournament_home(request):
    tournaments = Tournament.objects.order_by('-tournament_date').all()
    return render(request, 'hodor/tournament/home.html',
                  {
                      'tournaments': tournaments,
                  })


def tournament_builder(request):
    return render(request, 'hodor/tournament/builder.html')


def tournament_simul(request):
    battles = None
    error = None

    if request.method == 'POST':
        battles = []
        for left, right in (('attacker', 'defender'), ('defender', 'attacker')):

            attacker_army = request.POST['%s_army' % left]
            defender_army = request.POST['%s_army' % right]
            attacker_army_support_xp = request.POST.get('%s_army_support_xp' % left)
            defender_army_support_xp = request.POST.get('%s_army_support_xp' % right)
            attacker_army_support_xp = int(attacker_army_support_xp) if attacker_army_support_xp else 0
            defender_army_support_xp = int(defender_army_support_xp) if defender_army_support_xp else 0

            spells = {
                'attacker': [None, None, None, None],
                'defender': [None, None, None, None]
            }
            for attacker in ('attacker', 'defender'):
                for i in range(4):
                    spell_id = int(request.POST.get('spell_select_%s_%d' % (attacker, i), 0))
                    if spell_id:
                        spell = combat_spell(spell_id)

                        if i < spell.min_tu or i > spell.max_tu:
                            raise Exception('Cannot cast %s in %d' % (spell, i))

                        target = request.POST.get('spell_target_%s_%d' % (attacker, i))
                        spell_xp = int(request.POST.get('spell_xp_%s_%d' % (attacker, i))) / 100.0
                        if 0.01 > spell_xp > 1.0:
                            raise Exception("Spell XP not in range 1..100, got %d" % (spell_xp * 100))

                        # noinspection PyTypeChecker
                        spells[attacker][i] = SpellInCombat(
                            spell.spell_id, spell.name, spell.text_template, spell_xp, target, spell.spell_id == COUNTERSPELL_ID
                        )

            try:
                battle = battle_one_on_one(attacker_army, defender_army,
                                           attacker_army_support_xp / 100.0,
                                           defender_army_support_xp / 100.0,
                                           spells[left],
                                           spells[right],
                                           bool(request.POST.get('use_size_bonus')),
                                           )
                UserSimulation(army_attacker=attacker_army, army_defender=defender_army).save()

                battles.append(battle)
            except Exception as e:
                traceback.print_exc()
                error = str(e)

    combat_spells_by_groups = all_combat_spell_groups()

    return render(request, 'hodor/tournament/simul.html', {
        'battles': battles,
        'error': error,
        'combat_spells_by_groups': combat_spells_by_groups,
    })


def tournament_detail(request, tournament_id: int, tournament_slug: str):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_detail', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug}))

    return render(request, 'hodor/tournament/detail.html', {
        'tournament': tournament,
    })


def tournament_result(request, tournament_id: int, tournament_slug: str):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_result', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug}))

    if tournament.publicly_visible:
        tournament_results = {}
        for result in tournament.tournamentresult_set.all():
            if result.attacker_id not in tournament_results:
                tournament_results[result.attacker_id] = {}

            tournament_results[result.attacker_id][result.defender_id] = result

        return render(request, 'hodor/tournament/result.html', {
            'tournament': tournament,
            'tournament_submissions': tournament.tournamentsubmission_set.order_by(*tournament.result_type_submission_order_by()).all(),
            'tournament_results': tournament_results,
        })

    else:
        return render(request, 'hodor/tournament/result_unfinished.html', {
            'tournament': tournament,
            'tournament_submissions': tournament.tournamentsubmission_set.order_by(*tournament.result_type_submission_order_by())[:3],
        })


def tournament_result_player(request, tournament_id: int, tournament_slug: str, player_id: int):
    tournament = _get_publicly_visible_tournament(request, tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_result_player', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug, 'player_id': player_id}))

    tournament_submission = get_object_or_404(TournamentSubmission, pk=player_id)

    results = TournamentResult.objects.select_related('defender').filter(tournament=tournament).filter(Q(attacker__id=player_id) | Q(defender__id=player_id)).all()

    result_matrix = {}

hodor/templates/hodor/layout.html
{% load static %}{% load hodor_filters %}<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="icon" sizes="32x32" href="{% static 'favicon.ico' %}">
    <link href="{% static 'css/hodor.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="//unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css">
    <script src="//use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>

    {% get_from_settings 'ENABLE_GA_TAG' as enable_ga_tag %}
    {% if enable_ga_tag %}
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-188678642-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }

            gtag('js', new Date());

            gtag('config', 'UA-188678642-1');
        </script>
    {% endif %}

    <title>{% block title %}HODOR{% endblock %}</title>
    {% block css %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
    <div class="container">
        {% block navbar %}
            <a href="{% url 'hodor:tournament_home' %}">
                <span class="navbar-brand">SGM</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'hodor:tournament_home' %}">Pravidla</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'hodor:tournament_builder' %}">Builder</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'hodor:tournament_simul' %}">Simul</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'hodor:info_units' %}">Info-Jednotky</a>
                    </li>
                    {% block menu %}{% endblock %}
                </ul>
            </div>
        {% endblock %}
    </div>
</nav>

{% block content %}{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="//code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script src="//unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
{% block js %}{% endblock %}
</body>
</html>