hodor/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'hodor'

urlpatterns = []

if settings.WEB_HODOR_ENABLE_WEB:
    urlpatterns = [
        path('', RedirectView.as_view(pattern_name='hodor:tournament_home')),
        path('hodor/', views.simul, name='simul'),
        path('tournaments/', views.tournament_home, name='tournament_home'),
        path('tournaments/builder/', views.tournament_builder, name='tournament_builder'),
        path('tournaments/simul/', views.tournament_simul, name='tournament_simul'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/', views.tournament_detail, name='tournament_detail'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/result/', views.tournament_result, name='tournament_result'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/admin/', views.tournament_admin, name='tournament_admin'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/execute/', views.tournament_execute, name='tournament_execute'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/validate/', views.tournament_validate, name='tournament_validate'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/result/<int:player_id>/', views.tournament_result_player, name='tournament_result_player'),
        path('tournaments/<int:tournament_id>-<slug:tournament_slug>/result/<int:attacker_id>-vs-<int:defender_id>/', views.tournament_result_match, name='tournament_result_match'),
        path('ajax/units/', views.ajax_units, name='ajax_units'),
        path('info/units/', views.info_units, name='info_units'),
        path('info/sizes/', views.info_sizes, name='info_sizes'),
    ]

urlpatterns.append(
    path('ajax/simulate-gate/', views.ajax_simulate_gate, name='ajax_simulate_gate')
)

hodor/views.py
# Create your views here.
import json
import traceback

import jsonpickle
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from hodor.combat.battle import Battle
from hodor.combat.combatmodel import SpellInCombat
from hodor.combat.simulator import simulate_all
from hodor.combat.userinput import process_user_input, parse_input_file_autodetect, new_gate_units, parse_json
from hodor.data.provider import all_regular_units, combat_spell, COUNTERSPELL_ID, all_combat_spell_groups
from hodor.json import UnitFullInfoEncoder
from hodor.models import Tournament, TournamentResult, TournamentSubmission, UserSimulation
from hodor.tournament import execute_tournament, battle_one_on_one


def simul(request):
    if not settings.WEB_HODOR_ALLOW_PRECISE_SIMULATION:
        return render(request, 'hodor/simul/simul_disabled.html')

    # simulate heavily pre-scripted combat

    battles = []
    units_input = None
    gate_number = None
    input_gate_passed = None

    if request.method == 'POST':
        units_input = request.POST['units']
        gate_number = int(request.POST['gate_number'])
        input_gate_passed = int(request.POST['input_gate_passed']) if request.POST['input_gate_passed'] != '' else None

        gate_units_sets = new_gate_units(gate_number=gate_number, players_passed=input_gate_passed)

        for index, gate_units in enumerate(gate_units_sets):
            user_units = process_user_input(parse_input_file_autodetect(units_input))
            battle = Battle(user_units + gate_units, gate_number=gate_number, label='Army %d' % index,
                            verbose_result=True)
            battle.execute_battle()
            battles.append(battle)

        units_input = "\n".join('%s;%s;%d' % (u.nazev, ("%.4f" % (u.zkusenost / 100.0)).rstrip("0."), u.pocet) for u in
                                process_user_input(parse_input_file_autodetect(units_input)))

    return render(request, 'hodor/simul/simul.html', {
        'battles': battles,
        'units_input': units_input,
        'gate_number': gate_number,
        'input_gate_passed': input_gate_passed,
    })


@require_POST
@csrf_exempt  # no need for csrf here, on the other hand GET does not make sense
def ajax_simulate_gate(request):
    data = json.loads(request.body)

    attacker_units = process_user_input(parse_json(data['units']))
    battles = simulate_all(attacker_units, data['gate'], data['already_passed'])

    result = []

    for battle in battles:
        if battle.result_attacker + 0.05 < battle.result_defender:
            # solid victory
            result.append([battle.label, 'win'])
        elif battle.result_attacker < battle.result_defender:
            # close victory
            result.append([battle.label, 'near-win'])
        elif battle.result_attacker - 0.05 < battle.result_defender:
            # close defeat
            result.append([battle.label, 'near-loss'])
        else:
            # solid defeat
            result.append([battle.label, 'loss'])

    return JsonResponse({'result': result})


@cache_page(60 * 60)
def ajax_units(request):
    return JsonResponse({'units': all_regular_units()}, UnitFullInfoEncoder)


@permission_required('hodor.add_tournamentsubmission', raise_exception=True)
def tournament_admin(request, tournament_id: int, tournament_slug: str):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_admin', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug}))

    tournament_results = {}
    for result in tournament.tournamentresult_set.all():
        if result.attacker_id not in tournament_results:
            tournament_results[result.attacker_id] = {}

        tournament_results[result.attacker_id][result.defender_id] = result

    return render(request, 'hodor/tournament/admin.html', {
        'tournament': tournament,
        'tournament_submissions': tournament.tournamentsubmission_set.order_by(*(['valid'] + tournament.result_type_submission_order_by())).all(),
        'tournament_results': tournament_results,
    })


def tournament_home(request):
    tournaments = Tournament.objects.order_by('-tournament_date').all()
    return render(request, 'hodor/tournament/home.html',
                  {
                      'tournaments': tournaments,
                  })


def tournament_builder(request):
    return render(request, 'hodor/tournament/builder.html')


def tournament_simul(request):
    battles = None
    error = None

    if request.method == 'POST':
        battles = []
        for left, right in (('attacker', 'defender'), ('defender', 'attacker')):

            attacker_army = request.POST['%s_army' % left]
            defender_army = request.POST['%s_army' % right]
            attacker_army_support_xp = request.POST.get('%s_army_support_xp' % left)
            defender_army_support_xp = request.POST.get('%s_army_support_xp' % right)
            attacker_army_support_xp = int(attacker_army_support_xp) if attacker_army_support_xp else 0
            defender_army_support_xp = int(defender_army_support_xp) if defender_army_support_xp else 0

            spells = {
                'attacker': [None, None, None, None],
                'defender': [None, None, None, None]
            }
            for attacker in ('attacker', 'defender'):
                for i in range(4):
                    spell_id = int(request.POST.get('spell_select_%s_%d' % (attacker, i), 0))
                    if spell_id:
                        spell = combat_spell(spell_id)

                        if i < spell.min_tu or i > spell.max_tu:
                            raise Exception('Cannot cast %s in %d' % (spell, i))

                        target = request.POST.get('spell_target_%s_%d' % (attacker, i))
                        spell_xp = int(request.POST.get('spell_xp_%s_%d' % (attacker, i))) / 100.0
                        if 0.01 > spell_xp > 1.0:
                            raise Exception("Spell XP not in range 1..100, got %d" % (spell_xp * 100))

                        # noinspection PyTypeChecker
                        spells[attacker][i] = SpellInCombat(
                            spell.spell_id, spell.name, spell.text_template, spell_xp, target, spell.spell_id == COUNTERSPELL_ID
                        )

            try:
                battle = battle_one_on_one(attacker_army, defender_army,
                                           attacker_army_support_xp / 100.0,
                                           defender_army_support_xp / 100.0,
                                           spells[left],
                                           spells[right],
                                           bool(request.POST.get('use_size_bonus')),
                                           )
                UserSimulation(army_attacker=attacker_army, army_defender=defender_army).save()

                battles.append(battle)
            except Exception as e:
                traceback.print_exc()
                error = str(e)

    combat_spells_by_groups = all_combat_spell_groups()

    return render(request, 'hodor/tournament/simul.html', {
        'battles': battles,
        'error': error,
        'combat_spells_by_groups': combat_spells_by_groups,
    })


def tournament_detail(request, tournament_id: int, tournament_slug: str):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_detail', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug}))

    return render(request, 'hodor/tournament/detail.html', {
        'tournament': tournament,
    })


def tournament_result(request, tournament_id: int, tournament_slug: str):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_result', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug}))

    if tournament.publicly_visible:
        tournament_results = {}
        for result in tournament.tournamentresult_set.all():
            if result.attacker_id not in tournament_results:
                tournament_results[result.attacker_id] = {}

            tournament_results[result.attacker_id][result.defender_id] = result

        return render(request, 'hodor/tournament/result.html', {
            'tournament': tournament,
            'tournament_submissions': tournament.tournamentsubmission_set.order_by(*tournament.result_type_submission_order_by()).all(),
            'tournament_results': tournament_results,
        })

    else:
        return render(request, 'hodor/tournament/result_unfinished.html', {
            'tournament': tournament,
            'tournament_submissions': tournament.tournamentsubmission_set.order_by(*tournament.result_type_submission_order_by())[:3],
        })


def tournament_result_player(request, tournament_id: int, tournament_slug: str, player_id: int):
    tournament = _get_publicly_visible_tournament(request, tournament_id)
    if tournament.slug != tournament_slug:
        redirect(reverse('hodor:tournament_result_player', kwargs={'tournament_id': tournament.id, 'tournament_slug': tournament.slug, 'player_id': player_id}))

    tournament_submission = get_object_or_404(TournamentSubmission, pk=player_id)

    results = TournamentResult.objects.select_related('defender').filter(tournament=tournament).filter(Q(attacker__id=player_id) | Q(defender__id=player_id)).all()

    result_matrix = {}

hodor/templates/hodor/tournament/admin.html
{% extends 'hodor/tournament/layout.html' %}
{% load hodor_filters %}

{% block title %}SGM | Tournament {{ tournament.name }}{% endblock %}


{% block content %}
    <div class="container">
        <div class="row py-5 text-center">
            <div class="col">
                <form method="post" action="{% url 'hodor:tournament_validate' tournament_id=tournament.id tournament_slug=tournament.slug %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Validate</button>
                </form>
            </div>
            <div class="col">
                <form method="post" action="{% url 'hodor:tournament_execute' tournament_id=tournament.id tournament_slug=tournament.slug %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Simulate</button>
                </form>
            </div>
            <div class="col">
                <a class="btn btn-primary" href="{% url 'admin:hodor_tournament_change' tournament.id %}">Edit tournament</a>
            </div>
            <div class="col">
                <a class="btn btn-primary" href="{% url 'admin:hodor_tournamentsubmission_add' %}?tournament={{ tournament.id }}">Add submission</a>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Player</th>
                <th scope="col">Main</th>
                <th scope="col">Army</th>
                <th scope="col">Valid</th>
                <th scope="col">Power</th>
                <th scope="col">Recruit</th>
                <th scope="col">Validation Message</th>
                <th scope="col">Wins</th>
                <th scope="col">Avg RD</th>
                <th scope="col">hAr</th>
            </tr>
            </thead>
            {% for submission in tournament_submissions %}
                <tr{% if not submission.valid %} class="bg-warning"{% endif %}>
                    <td>{{ forloop.counter }}.</td>
                    <td>
                        <a href="{% url 'hodor:tournament_result_player' tournament_id=tournament.id tournament_slug=tournament.slug player_id=submission.id %}">{{ submission.player_name }}#{{ submission.player_id }}</a>
                    </td>
                    <td>
                        {{ submission.main_stack }}
                    </td>
                    <td>
                        <a href="{% url 'admin:hodor_tournamentsubmission_change' submission.id %}">
                            <pre><code>{{ submission.army }}</code></pre>
                        </a>
                    </td>
                    <td>
                        {{ submission.valid }}
                    </td>
                    <td>
                        {{ submission.army_power|thousand_format }}
                    </td>
                    <td>
                        {{ submission.recruit_tu }}
                    </td>
                    <td>
                        {{ submission.validation_message }}
                    </td>
                    <td>
                        {{ submission.wins }}
                    </td>
                    <td>
                        {{ submission.average_result_diff|percent:2 }}
                    </td>
                    <td>
                        {{ submission.area_taken|har20k|pm_int_thousands }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <h2>Results</h2>

    {% include 'hodor/tournament/fragments/results_table.html' with tournament_submissions=tournament_submissions tournament_results=tournament_results only %}
{% endblock %}

hodor/templates/hodor/tournament/builder.html
{% extends 'hodor/layout.html' %}
{% load hodor_filters %}
{% load static %}

<!--suppress HtmlFormInputWithoutLabel -->

{% block title %}SGM | Builder{% endblock %}

{% block js %}
    <script type="text/javascript">
        const URL_AJAX_UNITS = "{% url 'hodor:ajax_units' %}";
    </script>
    <script src="{% static 'js/builder.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h2 class="display-3">Builder</h2>

        <div class="table-responsive">
            <table class="table table-sm" id="units">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Jednotka</th>
                    <th scope="col" class="text-right">XP</th>
                    <th scope="col" class="text-right">Počet</th>
                    <th scope="col">Cíl</th>
                    <th scope="col">Druh</th>
                    <th scope="col">Typ</th>
                    <th scope="col" class="text-center">Phb</th>
                    <th scope="col" class="text-center">Ini</th>
                    <th scope="col" class="text-center">B</th>
                    <th scope="col" class="text-right">Síla</th>
                    <th scope="col" class="text-right">Síla&nbsp;celkem</th>
                    <th scope="col" class="text-right">Rekrut/TU</th>
                    <th scope="col" class="text-right">Rekrut&nbsp;TU</th>
                    <th scope="col" class="text-right">ZL</th>
                    <th scope="col" class="text-right">ZL*</th>
                    <th scope="col" class="text-right">MN</th>
                    <th scope="col" class="text-right">PP</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
                <tfoot>

                <tr class="total">
                    <th scope="col" class="unit_count">4</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col" class="text-right total_count"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col" class="text-right total_power"></th>
                    <th scope="col"></th>
                    <th scope="col" class="text-right total_recruit_tu"></th>
                    <th scope="col" class="text-right total_upkeep_gp"></th>
                    <th scope="col" class="text-right total_upkeep_gp_real"></th>
                    <th scope="col" class="text-right total_upkeep_mn"></th>
                    <th scope="col" class="text-right total_upkeep_pp"></th>
                </tr>
                </tfoot>
            </table>
        </div>

        <p>
            *) Reálný upkeep vč. vytlačování populace.
        </p>

        <h4>&darr; Toto poslat Savannahovi &darr;</h4>
        <small class="text-muted">
            <code>@Savannah#9217</code> na oficiálním MA discordu, nebo na ID 9217 MAštou
        </small>

        <div class="d-none">
            <table id="template-unit">
                <tbody>
                <tr class="builder-row">
                    <th scope="row" class="counter">1</th>
                    <td>
                        <select class="custom-select custom-select-sm unit change-trigger input-selector" style="min-width: 8em">
                            <option value="0">---</option>
                        </select>
                    </td>
                    <td>
                        <input type="number" class="form-control form-control-sm text-right xp change-trigger" value="40" min="1" max="100" style="min-width: 4em">
                    </td>
                    <td>
                        <input type="number" class="form-control form-control-sm text-right count change-trigger" value="1" min="1" style="min-width: 6em">
                    </td>
                    <td>
                        <select class="custom-select custom-select-sm target change-trigger " style="min-width: 6em">
                            <option value=""> ---</option>
                            <option value="dmg">dmg</option>
                            <option value="pocet">počet</option>
                            <option value="zivoty">životy</option>
                            <option value="iniciativa">ini</option>
                        </select>
                    </td>
                    <td class="flier"></td>
                    <td class="attack"></td>
                    <td class="text-center movement"></td>
                    <td class="initiative ini-block"></td>
                    <td class="text-center color"></td>
                    <td class="text-right power"></td>
                    <td class="text-right total_power"></td>
                    <td class="text-right recruit_per_tu"></td>
                    <td class="text-right">
                        <input type="number" class="form-control form-control-sm text-right recruit_tu ml-auto" style="width: 5em">
                    </td>
                    <td class="text-right gp"></td>
                    <td class="text-right gp_real"></td>
                    <td class="text-right mn"></td>
                    <td class="text-right pp"></td>
                </tr>
                </tbody>
            </table>
        </div>

        <textarea class="form-control my-4 result_text" rows="8"></textarea>

        <button type="button" class="btn btn-danger" id="reset">Reset</button>
    </div>
{% endblock %}

hodor/templates/hodor/tournament/home.html
{% extends 'hodor/layout.html' %}
{% load hodor_filters %}
{% load static %}

{% block title %}SGM | Pravidla{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="display-3">SGM League</h2>

        <p>
            Dámy a pánové,
        </p>
        <p>
            nahodil jsem projekt jménem <abbr title="Savannah's Great Melee">SGM</abbr> League &ndash; velká aréna, kde
            proti sobě bojují MAčkové armády. Každý hráč může udělat svojí armádu (podle omezení níže) a poslat jí do
            soutěže. Já pak udělám velkou simulaci &ndash;"každý s každým".
        </p>
        <p>
            Kdo bude mít nejvíce výher (v případě shody rozhoduje průměrný rozdíl ztrát) je šampion!
        </p>
        <p>
            A jelikož se jedná o turnaj, budou ceny! (viz níže)
        </p>

        <h3 class="display-4">Zadávání armád</h3>

        <p>
            Nejsnazší je vzít <a href="{% url 'hodor:tournament_builder' %}">SGM BUILDER</a> a výsledek poslat na <code>@Savannah#9217</code> na oficiálním MA discordu, nebo na ID
            9217 MAštou.
        </p>

        <div class="text-muted">
            <p>
                Starý postup: Armády zasílejte na soukromou zprávu na <code>@Savannah#9217</code> na oficiálním MA discordu, nebo na ID 9217
                MAštou. Doporučuji si pro ulehčení stáhnout <a href="{% static 'docs/savannahs-great-melee.xlsx' %}">tento excel</a>, kde si můžete věci "vyklikat"!
            </p>

            <p>
                Formát zadání je následující:
            </p>

            <div class="my-3">
                <code>
                    Polární bouře;0.4;1000<br>
                    Lich;1;50<br>
                    Zlatý drak;1;5;pocet
                </code>
            </div>

            <p>
                Kde první je název jednotky (přesný, vč. háčků/čárek a velikosti písmen), následuje zkušenost (0.4 = 40%) a
                poslední je počet. Za počtem může být i "na co útočit", což je jedna z hodnot <code>pocet</code>,<code>dmg</code>, <code>zivoty</code>, <code>iniciativa</code>.
                Jednotky obránce jdou vždy na dmg, stejně pokud neuvedete jinak pro útočníka ;)
            </p>
        </div>

        V boji nejsou kouzla ani podpory (not yet anyways :wink: ), útočí se vždy do 100% (aka nejde se do 80%).

        <h3 class="display-4">Turnaje</h3>

        <ul>
            {% for tournament in tournaments %}
                <li><a href="{{ tournament.get_absolute_url }}">{{ tournament.name }}</a> ({{ tournament.tournament_date }})</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

hodor/templates/hodor/tournament/simul.html
{% extends 'hodor/layout.html' %}
{% load hodor_filters %}
{% load static %}

<!--suppress HtmlFormInputWithoutLabel -->

{% block title %}SGM | Simul{% endblock %}

{% block js %}
    <script src="{% static 'js/player_simul.js' %}"></script>
    <script src="{% static 'js/display_battle.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="fixed-top container" id="copied-to-clipboard-alert" style="display: none">
        <div class="alert alert-success">Uloženo do schránky!</div>
    </div>

    <div class="container">
        <h2 class="display-3">Simul soubojů</h2>
        <form method="post" action="{% url 'hodor:tournament_simul' %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-12 col-md">
                    <h4>Útočník

                        <button type="button" class="btn btn-sm btn-outline-primary" id="history_prev_attacker">&larr;</button>
                        <small>
                            <span id="attacker_history_index">0</span> / <span id="attacker_history_length">0</span>
                        </small>
                        <button type="button" class="btn btn-sm btn-outline-primary" id="history_next_attacker">&rarr;</button>

                        <button type="button" class="btn btn-sm btn-outline-primary float-right" title="Copy input with spells to clipboard." id="attacker-copy-to-clipboard">
                            <i class="far fa-copy"></i>
                        </button>
                    </h4>
                    <textarea class="form-control" rows="8" name="attacker_army" id="attacker_army"></textarea>
                    <div class="form-group">
                        <label for="exampleInputEmail1">XP podpor</label>
                        <input type="number" class="form-control" name="attacker_army_support_xp" id="attacker_army_support_xp" value="0" min="0" max="100">
                        <small id="emailHelp" class="form-text text-muted">0 = bez podpor, 100 = 19% max</small>
                    </div>

                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='attacker' round=0 only %}
                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='attacker' round=1 only %}
                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='attacker' round=2 only %}
                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='attacker' round=3 only %}
                </div>
                <div class="col-12 col-md">
                    <h4>Obránce

                        <button type="button" class="btn btn-sm btn-outline-primary" id="history_prev_defender">&larr;</button>
                        <small>
                            <span id="defender_history_index">0</span> / <span id="defender_history_length">0</span>
                        </small>
                        <button type="button" class="btn btn-sm btn-outline-primary" id="history_next_defender">&rarr;</button>

                        <button type="button" class="btn btn-sm btn-outline-primary float-right" title="Copy input with spells to clipboard." id="defender-copy-to-clipboard">
                            <i class="far fa-copy"></i>
                        </button>
                    </h4>
                    <textarea class="form-control" rows="8" name="defender_army" id="defender_army"></textarea>
                    <div class="form-group">
                        <label for="exampleInputEmail1">XP podpor</label>
                        <input type="number" class="form-control" name="defender_army_support_xp" id="defender_army_support_xp" value="0" min="0" max="100">
                        <small id="emailHelp" class="form-text text-muted">0 = bez podpor, 100 = 19% max</small>
                    </div>

                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='defender' round=0 only %}
                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='defender' round=1 only %}
                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='defender' round=2 only %}
                    {% include 'hodor/tournament/fragments/spell_select.html' with combat_spells_by_groups=combat_spells_by_groups attacker='defender' round=3 only %}
                </div>
            </div>

            <div class="row text-center">
                <div class="form-check mx-auto">
                    <input type="checkbox" class="form-check-input" id="use_size_bonus" name="use_size_bonus">
                    <label class="form-check-label" for="use_size_bonus">Bonusy podle velikostí</label>
                    <a href="{% url 'hodor:info_sizes' %}"><i class="fas fa-question-circle"></i></a>
                </div>
            </div>

            <div class="row text-center my-4">
                <button type="submit" class="btn btn-primary mx-auto" id="submit">Simulovat!</button>
            </div>
        </form>

        {% if error %}
            <div class="row">
                <div class="col text-center">
                    <div class="bg-warning text-dark">
                        Chyba: {{ error }}
                    </div>
                </div>
            </div>
        {% endif %}

        {% if battles %}
            <ul class="nav nav-tabs battle-tabs" id="myTab" role="tablist">
                {% for battle in battles %}
                    <li class="nav-item col-6 text-center">
                        <a class="nav-link px-2 py-1 {% if forloop.first %} active{% endif %}"
                           id="profile-tab" data-toggle="tab" href="#battle_{{ forloop.counter }}">
                            {% if forloop.first %}Útok{% else %}Obrana{% endif %}
                            <br class="d-block d-md-none"/>
                            {% if battle.label is not None %}{{ battle.label }}<br/>{% endif %}{{ battle.result_attacker|percent }} : {{ battle.result_defender|percent }}
                        </a>
                    </li>
                {% endfor %}
            </ul>

            <div class="row">
                <div class="col">
                    <div class="tab-content battles-wrapper">
                        {% for battle in battles %}
                            <div class="tab-pane fade battle {% if forloop.first %} show active{% endif %}" id="battle_{{ forloop.counter }}">
                                {% for event in battle.log_events %}
                                    {% render_battle_log_entry event %}
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}